export const favs = [
  "Sitcoms",
  "Brooklyn Nine-Nine",
  "Gina Linetti from Brooklyn Nine-Nine",
  "Parks and Recreations",
  "Modern Family",
  "The Office(US)",
  "Friends",
  "Beetlejuice",
  "Coraline",
  "Card Captor Sakura",
  "Penguindrum",
  "Revolutionary Girl Utena",
  "Made In Abyss",
  "Doodle",
  "Mysteries novels",
  "Fantasy novels",
  "Horror novels",
  "Boulet Brother's Dragula",
  "Drag Artists",
  "Travelling",
  "Kobujime",
  "Sake",
  "etc ...",
];
